apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stateless-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stateless-rs
  template:
    metadata:
      labels:
        app: stateless-rs
    spec:
      containers:
      - name: nginx
        image: nginx
